require('dotenv').config();

const db = require('./api/util/db.js');

async function updateQuests(){
  await db.query("DROP TABLE stop,quest,reward,quest_reward,report");
  await db.query("CREATE TABLE quest (id SERIAL PRIMARY KEY, quest VARCHAR(100), active BOOLEAN DEFAULT TRUE)");
  await db.query("CREATE TABLE stop (id SERIAL PRIMARY KEY, name VARCHAR(50), loc POINT)");
  await db.query("CREATE TABLE reward (id INT PRIMARY KEY, reward VARCHAR(50), shiny BOOLEAN DEFAULT FALSE, icon VARCHAR(100))");
  await db.query("CREATE TABLE quest_reward (id SERIAL PRIMARY KEY, quest_id INT REFERENCES quest(id), reward_id INT REFERENCES reward(id))");
  await db.query("CREATE TABLE report (id SERIAL PRIMARY KEY, user_id INT NOT NULL REFERENCES discord_user(id), stop_id INT NOT NULL REFERENCES stop(id), quest_id INT NOT NULL REFERENCES quest(id), reward_id INT REFERENCES reward(id))");
  for(s in stops){
    await db.query("INSERT INTO stop (name, loc) VALUES ($1, point($2, $3))", [stops[s]['name'], stops[s]['lat'], stops[s]['long']]);
  }
  console.log('Stops Imported');
  for(q in quests){
    await db.query("INSERT INTO quest (quest, active) VALUES ($1, $2)", [quests[q]['quest'], quests[q]['active']]);
  }
  console.log('Quests Imported');
  for(r in rewards){
    var icon = rewards[r]['icon'];
    if(icon === undefined){
      icon = "icon_" + rewards[r]['reward'];
    }
    if(rewards[r]['shiny'] !== undefined){
      await db.query("INSERT INTO reward (id, reward, shiny, icon) VALUES ($1, $2, $3, $4)", [rewards[r]['id'], rewards[r]['reward'].charAt(0).toUpperCase() + rewards[r]['reward'].slice(1), rewards[r]['shiny'], icon]);
    } else {
      await db.query("INSERT INTO reward (id, reward, icon) VALUES ($1, $2, $3)", [rewards[r]['id'], rewards[r]['reward'].charAt(0).toUpperCase() + rewards[r]['reward'].slice(1), icon]);      
    }
  }
  console.log('Rewards Imported');
  for(qr in quest_rewards){
    await db.query("INSERT INTO quest_reward (quest_id, reward_id) VALUES ($1, $2)", [quest_rewards[qr]['quest_id'], quest_rewards[qr]['reward_id']]);
  }
  console.log('Quest - Reward Relationship Created');
  process.exit();
}

var stops = [
  {
    "name": "University Commons",
    "lat": 43.079686999999964,
    "long": -77.68256400000016
  },
  {
    "name": "Red Barn",
    "lat": 43.084354,
    "long": -77.684514
  },
  {
    "name": "Display of Grace",
    "lat": 43.085411,
    "long": -77.681918
  },
  {
    "name": "Windmills",
    "lat": 43.08564500000031,
    "long": -77.6809729999998
  },
  {
    "name": "CAST Girder",
    "lat": 43.08515299999967,
    "long": -77.67987600000008
  },
  {
    "name": "North GCCIS",
    "lat": 43.084734,
    "long": -77.67997
  },
  {
    "name": "Sillicon Ingot",
    "lat": 43.08429900000013,
    "long": -77.67913499999992
  },
  {
    "name": "South GCCIS",
    "lat": 43.08371500000004,
    "long": -77.6796040000003
  },
  {
    "name": "GV",
    "lat": 43.082931,
    "long": -77.679605
  },
  {
    "name": "GV Fountain",
    "lat": 43.083198,
    "long": -77.678468
  },
  {
    "name": "Gosnell Atrium",
    "lat": 43.083562999999,
    "long": -77.67735100000034
  },
  {
    "name": "Susie Lewis",
    "lat": 43.08311399999976,
    "long": -77.67693100000032
  },
  {
    "name": "Marie Nitzman",
    "lat": 43.08384400000034,
    "long": -77.67591799999992
  },
  {
    "name": "Java Wallys",
    "lat": 43.08412799999969,
    "long": -77.6763019999998
  },
  {
    "name": "Tau Beta Pi",
    "lat": 43.084245999999766,
    "long": -77.6773929999996
  },
  {
    "name": "Kate Gleason Bust",
    "lat": 43.08427499999976,
    "long": -77.67860599999979
  },
  {
    "name": "Rocky Zen",
    "lat": 43.085192999999634,
    "long": -77.67879299999994
  },
  {
    "name": "Pi Quad",
    "lat": 43.085166000000385,
    "long": -77.67840900000009
  },
  {
    "name": "Puu-Chang",
    "lat": 43.08579399999979,
    "long": -77.67739099999983
  },
  {
    "name": "Triple Barrel",
    "lat": 43.08493699999976,
    "long": -77.67748799999993
  },
  {
    "name": "Women In Arms",
    "lat": 43.08522100000035,
    "long": -77.67689099999991
  },
  {
    "name": "Squiggle Bench",
    "lat": 43.085094,
    "long": -77.676837
  },
  {
    "name": "Eastman Quad",
    "lat": 43.08464,
    "long": -77.676451
  },
  {
    "name": "Yasuji Tojo",
    "lat": 43.084906,
    "long": -77.675743
  },
  {
    "name": "Artful Bench",
    "lat": 43.085125,
    "long": -77.675464
  },
  {
    "name": "Lynn Skvarek",
    "lat": 43.085768,
    "long": -77.675507
  },
  {
    "name": "Time Capsule",
    "lat": 43.085047,
    "long": -77.674305
  },
  {
    "name": "SAU",
    "lat": 43.084138,
    "long": -77.674563
  },
  {
    "name": "Polisseni",
    "lat": 43.083135,
    "long": -77.674778
  },
  {
    "name": "Gazebo",
    "lat": 43.082618,
    "long": -77.672675
  },
  {
    "name": "Spider",
    "lat": 43.081944,
    "long": -77.671387
  },
  {
    "name": "Interfaith",
    "lat": 43.084123,
    "long": -77.673597
  },
  {
    "name": "Legacy Walk",
    "lat": 43.084311,
    "long": -77.672975
  },
  {
    "name": "Greek Rock",
    "lat": 43.084091,
    "long": -77.672846
  },
  {
    "name": "Tiger Chair",
    "lat": 43.085314,
    "long": -77.672739
  },
  {
    "name": "Marcia Ellingson Courtyard",
    "lat": 43.084264,
    "long": -77.672288
  },
  {
    "name": "Kevin Smith",
    "lat": 43.084373,
    "long": -77.670572
  },
  {
    "name": "Marcia Ellingson Garden",
    "lat": 43.083762,
    "long": -77.669907
  },
  {
    "name": "Kapp Delta Rho",
    "lat": 43.084326,
    "long": -77.669435
  },
  {
    "name": "Balance",
    "lat": 43.084514,
    "long": -77.668705
  },
  {
    "name": "Wetlands",
    "lat": 43.083339,
    "long": -77.666023
  },
  {
    "name": "9/11 Memorial",
    "lat": 43.084796,
    "long": -77.668018
  },
  {
    "name": "NRH Post Office",
    "lat": 43.084953,
    "long": -77.66701
  },
  {
    "name": "Echo Point",
    "lat": 43.085361,
    "long": -77.667675
  },
  {
    "name": "Whispering Wall",
    "lat": 43.08558,
    "long": -77.667525
  },
  {
    "name": "Bench of Legs",
    "lat": 43.086269,
    "long": -77.667825
  },
  {
    "name": "Concrete Tor",
    "lat": 43.086677,
    "long": -77.668447
  },
  {
    "name": "Split Cube",
    "lat": 43.086865,
    "long": -77.667739
  },
  {
    "name": "LBJ",
    "lat": 43.087607,
    "long": -77.667839
  },
  {
    "name": "Briggs Place",
    "lat": 43.087482,
    "long": -77.66892
  },
  {
    "name": "Orchid Tryptich",
    "lat": 43.087187,
    "long": -77.668618
  },
  {
    "name": "North Gate",
    "lat": 43.092005,
    "long": -77.674756
  },
  {
    "name": "RIT",
    "lat": 43.09235,
    "long": -77.666109
  },
  {
    "name": "Raddison",
    "lat": 43.0916,
    "long": -77.6636
  },
  {
    "name": "Park Point North",
    "lat": 43.092632,
    "long": -77.65907
  },
  {
    "name": "Park Point Clocktower",
    "lat": 43.091987,
    "long": -77.656611
  },
  {
    "name": "Barnes and Noble",
    "lat": 43.092007,
    "long": -77.655456
  },
  {
    "name": "Park Point East",
    "lat": 43.089842,
    "long": -77.655594
  },
  {
    "name": "Province",
    "lat": 43.086408,
    "long": -77.655773
  }
];

var quests = [
  {
    "quest": "Various",
    "active": true
  },
  {
    "quest": "Catch 3 Grass, Water, or Fire-type Pokemon",
    "active": true
  },
  {
    "quest": "Spin 10 Pokestops",
    "active": true
  },
  {
    "quest": "Use 5 Razz Berries to Help Catch Pokemon",
    "active": true
  },
  {
    "quest": "Catch 7 Flying, Psychic, or Dark-type Pokemon",
    "active": true
  },
  {
    "quest": "Catch 5 Electric, Normal, or Posion-type Pokemon",
    "active": true
  },
  {
    "quest": "Catch 10 Ice-type Pokemon",
    "active": true
  },
  {
    "quest": "Catch 10 Ground-type Pokemon",
    "active": true
  },
  {
    "quest": "Catch 5 Fighting-type Pokemon",
    "active": true
  },
  {
    "quest": "Use 10 Pinap Berries While Catching Pokemon",
    "active": true
  },
  {
    "quest": "Catch 10 Pokemon",
    "active": true
  },
  {
    "quest": "Catch 5 Pokemon with Weather Boost",
    "active": true
  },
  {
    "quest": "Catch a Dragon-type Pokemon",
    "active": true
  },
  {
    "quest": "Use 5 Berries to Help Catch Pokemon",
    "active": true
  },
  {
    "quest": "Use an Item to Evolve a Pokemon",
    "active": true
  },
  {
    "quest": "Power Up a Pokemon 5 Times",
    "active": true
  },
  {
    "quest": "Transfer 3 Pokemon",
    "active": true
  },
  {
    "quest": "Trade a Pokemon",
    "active": true
  },
  {
    "quest": "Earn 5 Candies Walking with Your Buddy",
    "active": true
  },
  {
    "quest": "Send 2 Gifts to Friends",
    "active": true
  },
  {
    "quest": "Hatch an Egg",
    "active": true
  },
  {
    "quest": "Hatch 3 Eggs",
    "active": true
  },
  {
    "quest": "Hatch 5 Eggs",
    "active": true
  },
  {
    "quest": "Win 5 Raids",
    "active": true
  },
  {
    "quest": "Win 5 Gym Battles",
    "active": true
  },
  {
    "quest": "Battle in a Gym",
    "active": true
  },
  {
    "quest": "Battle in a Gym 5 Times",
    "active": true
  },
  {
    "quest": "Win a Gym Battle",
    "active": true
  },
  {
    "quest": "User a Super Effective Charged Attack in a Gym Battle 7 Times",
    "active": true
  },
  {
    "quest": "Win 3 Gym Battles",
    "active": true
  },
  {
    "quest": "Battle in a Raid",
    "active": true
  },
  {
    "quest": "Win a Level 3 or Higher Raid",
    "active": true
  },
  {
    "quest": "Make 3 Great Throws",
    "active": true
  },
  {
    "quest": "Make 5 Great Curveball Throws in a Row",
    "active": true
  },
  {
    "quest": "Make 5 Nice Throws",
    "active": true
  },
  {
    "quest": "Make 3 Great Throws in a Row",
    "active": true
  },
  {
    "quest": "Make 3 Excellent Throws in a Row",
    "active": true
  },
  {
    "quest": "Hoenn Celebration: Catch 10 Zigzagoon or Taillow",
    "active": true
  },
  {
    "quest": "Hoenn Celebration: Hatch 2 Eggs",
    "active": true
  },
  {
    "quest": "Hoenn Celebration: Evolve 3 Wurmple",
    "active": true
  }
];

var rewards = [
   {
      "id":0,
      "reward":"encounter"
   },
   {
      "id":1,
      "reward":"bulbasaur",
      "shiny":true
   },
   {
      "id":2,
      "reward":"ivysaur",
      "shiny":true
   },
   {
      "id":3,
      "reward":"venusaur",
      "shiny":true
   },
   {
      "id":4,
      "reward":"charmander",
      "shiny":true
   },
   {
      "id":5,
      "reward":"charmeleon",
      "shiny":true
   },
   {
      "id":6,
      "reward":"charizard",
      "shiny":true
   },
   {
      "id":7,
      "reward":"squirtle",
      "shiny":true
   },
   {
      "id":8,
      "reward":"wartortle",
      "shiny":true
   },
   {
      "id":9,
      "reward":"blastoise",
      "shiny":true
   },
   {
      "id":10,
      "reward":"caterpie",
      "shiny":true
   },
   {
      "id":11,
      "reward":"metapod",
      "shiny":true
   },
   {
      "id":12,
      "reward":"butterfree",
      "shiny":true
   },
   {
      "id":13,
      "reward":"weedle"
   },
   {
      "id":14,
      "reward":"kakuna"
   },
   {
      "id":15,
      "reward":"beedrill"
   },
   {
      "id":16,
      "reward":"pidgey"
   },
   {
      "id":17,
      "reward":"pidgeotto"
   },
   {
      "id":18,
      "reward":"pidgeot"
   },
   {
      "id":19,
      "reward":"rattata"
   },
   {
      "id":20,
      "reward":"raticate"
   },
   {
      "id":21,
      "reward":"spearow"
   },
   {
      "id":22,
      "reward":"fearow"
   },
   {
      "id":23,
      "reward":"ekans"
   },
   {
      "id":24,
      "reward":"arbok"
   },
   {
      "id":25,
      "reward":"pikachu",
      "shiny":true
   },
   {
      "id":26,
      "reward":"raichu",
      "shiny":true
   },
   {
      "id":27,
      "reward":"sandshrew",
      "shiny":true
   },
   {
      "id":28,
      "reward":"sandslash",
      "shiny":true
   },
   {
      "id":29,
      "reward":"nidoran-f",
      "shiny":true
   },
   {
      "id":30,
      "reward":"nidorina",
      "shiny":true
   },
   {
      "id":31,
      "reward":"nidoqueen",
      "shiny":true
   },
   {
      "id":32,
      "reward":"nidoran-m"
   },
   {
      "id":33,
      "reward":"nidorino"
   },
   {
      "id":34,
      "reward":"nidoking"
   },
   {
      "id":35,
      "reward":"clefairy"
   },
   {
      "id":36,
      "reward":"clefable"
   },
   {
      "id":37,
      "reward":"vulpix"
   },
   {
      "id":38,
      "reward":"ninetales"
   },
   {
      "id":39,
      "reward":"jigglypuff"
   },
   {
      "id":40,
      "reward":"wigglytuff"
   },
   {
      "id":41,
      "reward":"zubat"
   },
   {
      "id":42,
      "reward":"golbat"
   },
   {
      "id":43,
      "reward":"oddish"
   },
   {
      "id":44,
      "reward":"gloom"
   },
   {
      "id":45,
      "reward":"vileplume"
   },
   {
      "id":46,
      "reward":"paras"
   },
   {
      "id":47,
      "reward":"parasect"
   },
   {
      "id":48,
      "reward":"venonat"
   },
   {
      "id":49,
      "reward":"venomoth"
   },
   {
      "id":50,
      "reward":"diglett"
   },
   {
      "id":51,
      "reward":"dugtrio"
   },
   {
      "id":52,
      "reward":"meowth"
   },
   {
      "id":53,
      "reward":"persian"
   },
   {
      "id":54,
      "reward":"psyduck"
   },
   {
      "id":55,
      "reward":"golduck"
   },
   {
      "id":56,
      "reward":"mankey"
   },
   {
      "id":57,
      "reward":"primeape"
   },
   {
      "id":58,
      "reward":"growlithe",
      "shiny":true
   },
   {
      "id":59,
      "reward":"arcanine",
      "shiny":true
   },
   {
      "id":60,
      "reward":"poliwag"
   },
   {
      "id":61,
      "reward":"poliwhirl"
   },
   {
      "id":62,
      "reward":"poliwrath"
   },
   {
      "id":63,
      "reward":"abra"
   },
   {
      "id":64,
      "reward":"kadabra"
   },
   {
      "id":65,
      "reward":"alakazam"
   },
   {
      "id":66,
      "reward":"machop"
   },
   {
      "id":67,
      "reward":"machoke"
   },
   {
      "id":68,
      "reward":"machamp"
   },
   {
      "id":69,
      "reward":"bellsprout"
   },
   {
      "id":70,
      "reward":"weepinbell"
   },
   {
      "id":71,
      "reward":"victreebel"
   },
   {
      "id":72,
      "reward":"tentacool"
   },
   {
      "id":73,
      "reward":"tentacruel"
   },
   {
      "id":74,
      "reward":"geodude",
      "shiny":true
   },
   {
      "id":75,
      "reward":"graveler",
      "shiny":true
   },
   {
      "id":76,
      "reward":"golem",
      "shiny":true
   },
   {
      "id":77,
      "reward":"ponyta",
      "shiny":true
   },
   {
      "id":78,
      "reward":"rapidash",
      "shiny":true
   },
   {
      "id":79,
      "reward":"slowpoke"
   },
   {
      "id":80,
      "reward":"slowbro"
   },
   {
      "id":81,
      "reward":"magnemite",
      "shiny":true
   },
   {
      "id":82,
      "reward":"magneton",
      "shiny":true
   },
   {
      "id":83,
      "reward":"farfetchd"
   },
   {
      "id":84,
      "reward":"doduo"
   },
   {
      "id":85,
      "reward":"dodrio"
   },
   {
      "id":86,
      "reward":"seel"
   },
   {
      "id":87,
      "reward":"dewgong"
   },
   {
      "id":88,
      "reward":"grimer",
      "shiny":true
   },
   {
      "id":89,
      "reward":"muk",
      "shiny":true
   },
   {
      "id":90,
      "reward":"shellder",
      "shiny":true
   },
   {
      "id":91,
      "reward":"cloyster",
      "shiny":true
   },
   {
      "id":92,
      "reward":"gastly",
      "shiny":true
   },
   {
      "id":93,
      "reward":"haunter",
      "shiny":true
   },
   {
      "id":94,
      "reward":"gengar",
      "shiny":true
   },
   {
      "id":95,
      "reward":"onix"
   },
   {
      "id":96,
      "reward":"drowzee",
      "shiny":true
   },
   {
      "id":97,
      "reward":"hypno",
      "shiny":true
   },
   {
      "id":98,
      "reward":"krabby",
      "shiny":true
   },
   {
      "id":99,
      "reward":"kingler",
      "shiny":true
   },
   {
      "id":100,
      "reward":"voltorb"
   },
   {
      "id":101,
      "reward":"electrode"
   },
   {
      "id":102,
      "reward":"exeggcute"
   },
   {
      "id":103,
      "reward":"exeggutor"
   },
   {
      "id":104,
      "reward":"cubone",
      "shiny":true
   },
   {
      "id":105,
      "reward":"marowak",
      "shiny":true
   },
   {
      "id":106,
      "reward":"hitmonlee"
   },
   {
      "id":107,
      "reward":"hitmonchan"
   },
   {
      "id":108,
      "reward":"lickitung"
   },
   {
      "id":109,
      "reward":"koffing"
   },
   {
      "id":110,
      "reward":"weezing"
   },
   {
      "id":111,
      "reward":"rhyhorn"
   },
   {
      "id":112,
      "reward":"rhydon"
   },
   {
      "id":113,
      "reward":"chansey"
   },
   {
      "id":114,
      "reward":"tangela"
   },
   {
      "id":115,
      "reward":"kangaskhan"
   },
   {
      "id":116,
      "reward":"horsea"
   },
   {
      "id":117,
      "reward":"seadra"
   },
   {
      "id":118,
      "reward":"goldeen"
   },
   {
      "id":119,
      "reward":"seaking"
   },
   {
      "id":120,
      "reward":"staryu"
   },
   {
      "id":121,
      "reward":"starmie"
   },
   {
      "id":122,
      "reward":"mr-mime"
   },
   {
      "id":123,
      "reward":"scyther"
   },
   {
      "id":124,
      "reward":"jynx"
   },
   {
      "id":125,
      "reward":"electabuzz",
      "shiny":true
   },
   {
      "id":126,
      "reward":"magmar",
      "shiny":true
   },
   {
      "id":127,
      "reward":"pinsir",
      "shiny":true
   },
   {
      "id":128,
      "reward":"tauros"
   },
   {
      "id":129,
      "reward":"magikarp",
      "shiny":true
   },
   {
      "id":130,
      "reward":"gyarados",
      "shiny":true
   },
   {
      "id":131,
      "reward":"lapras"
   },
   {
      "id":132,
      "reward":"ditto"
   },
   {
      "id":133,
      "reward":"eevee",
      "shiny":true
   },
   {
      "id":134,
      "reward":"vaporeon",
      "shiny":true
   },
   {
      "id":135,
      "reward":"jolteon",
      "shiny":true
   },
   {
      "id":136,
      "reward":"flareon",
      "shiny":true
   },
   {
      "id":137,
      "reward":"porygon"
   },
   {
      "id":138,
      "reward":"omanyte",
      "shiny":true
   },
   {
      "id":139,
      "reward":"omastar",
      "shiny":true
   },
   {
      "id":140,
      "reward":"kabuto",
      "shiny":true
   },
   {
      "id":141,
      "reward":"kabutops",
      "shiny":true
   },
   {
      "id":142,
      "reward":"aerodactyl",
      "shiny":true
   },
   {
      "id":143,
      "reward":"snorlax"
   },
   {
      "id":144,
      "reward":"articuno",
      "shiny":true
   },
   {
      "id":145,
      "reward":"zapdos",
      "shiny":true
   },
   {
      "id":146,
      "reward":"moltres",
      "shiny":true
   },
   {
      "id":147,
      "reward":"dratini",
      "shiny":true
   },
   {
      "id":148,
      "reward":"dragonair",
      "shiny":true
   },
   {
      "id":149,
      "reward":"dragonite",
      "shiny":true
   },
   {
      "id":150,
      "reward":"mewtwo"
   },
   {
      "id":151,
      "reward":"mew"
   },
   {
      "id":152,
      "reward":"chikorita",
      "shiny":true
   },
   {
      "id":153,
      "reward":"bayleef",
      "shiny":true
   },
   {
      "id":154,
      "reward":"meganium",
      "shiny":true
   },
   {
      "id":155,
      "reward":"cyndaquil",
      "shiny":true
   },
   {
      "id":156,
      "reward":"quilava",
      "shiny":true
   },
   {
      "id":157,
      "reward":"typhlosion",
      "shiny":true
   },
   {
      "id":158,
      "reward":"totodile",
      "shiny":true
   },
   {
      "id":159,
      "reward":"croconaw",
      "shiny":true
   },
   {
      "id":160,
      "reward":"feraligatr",
      "shiny":true
   },
   {
      "id":161,
      "reward":"sentret"
   },
   {
      "id":162,
      "reward":"furret"
   },
   {
      "id":163,
      "reward":"hoothoot"
   },
   {
      "id":164,
      "reward":"noctowl"
   },
   {
      "id":165,
      "reward":"ledyba"
   },
   {
      "id":166,
      "reward":"ledian"
   },
   {
      "id":167,
      "reward":"spinarak"
   },
   {
      "id":168,
      "reward":"ariados"
   },
   {
      "id":169,
      "reward":"crobat"
   },
   {
      "id":170,
      "reward":"chinchou"
   },
   {
      "id":171,
      "reward":"lanturn"
   },
   {
      "id":172,
      "reward":"pichu",
      "shiny":true
   },
   {
      "id":173,
      "reward":"cleffa"
   },
   {
      "id":174,
      "reward":"igglybuff"
   },
   {
      "id":175,
      "reward":"togepi",
      "shiny":true
   },
   {
      "id":176,
      "reward":"togetic",
      "shiny":true
   },
   {
      "id":177,
      "reward":"natu",
      "shiny":true
   },
   {
      "id":178,
      "reward":"xatu",
      "shiny":true
   },
   {
      "id":179,
      "reward":"mareep",
      "shiny":true
   },
   {
      "id":180,
      "reward":"flaaffy",
      "shiny":true
   },
   {
      "id":181,
      "reward":"ampharos",
      "shiny":true
   },
   {
      "id":182,
      "reward":"bellossom"
   },
   {
      "id":183,
      "reward":"marill",
      "shiny":true
   },
   {
      "id":184,
      "reward":"azumarill",
      "shiny":true
   },
   {
      "id":185,
      "reward":"sudowoodo"
   },
   {
      "id":186,
      "reward":"politoed"
   },
   {
      "id":187,
      "reward":"hoppip"
   },
   {
      "id":188,
      "reward":"skiploom"
   },
   {
      "id":189,
      "reward":"jumpluff"
   },
   {
      "id":190,
      "reward":"aipom"
   },
   {
      "id":191,
      "reward":"sunkern",
      "shiny":true
   },
   {
      "id":192,
      "reward":"sunflora",
      "shiny":true
   },
   {
      "id":193,
      "reward":"yanma"
   },
   {
      "id":194,
      "reward":"wooper"
   },
   {
      "id":195,
      "reward":"quagsire"
   },
   {
      "id":196,
      "reward":"espeon",
      "shiny":true
   },
   {
      "id":197,
      "reward":"umbreon",
      "shiny":true
   },
   {
      "id":198,
      "reward":"murkrow",
      "shiny":true
   },
   {
      "id":199,
      "reward":"slowking"
   },
   {
      "id":200,
      "reward":"misdreavus",
      "shiny":true
   },
   {
      "id":201,
      "reward":"unown"
   },
   {
      "id":202,
      "reward":"wobbuffet"
   },
   {
      "id":203,
      "reward":"girafarig"
   },
   {
      "id":204,
      "reward":"pineco",
      "shiny":true
   },
   {
      "id":205,
      "reward":"forretress",
      "shiny":true
   },
   {
      "id":206,
      "reward":"dunsparce"
   },
   {
      "id":207,
      "reward":"gligar"
   },
   {
      "id":208,
      "reward":"steelix"
   },
   {
      "id":209,
      "reward":"snubbull",
      "shiny":true
   },
   {
      "id":210,
      "reward":"granbull",
      "shiny":true
   },
   {
      "id":211,
      "reward":"qwilfish"
   },
   {
      "id":212,
      "reward":"scizor"
   },
   {
      "id":213,
      "reward":"shuckle"
   },
   {
      "id":214,
      "reward":"heracross"
   },
   {
      "id":215,
      "reward":"sneasel"
   },
   {
      "id":216,
      "reward":"teddiursa"
   },
   {
      "id":217,
      "reward":"ursaring"
   },
   {
      "id":218,
      "reward":"slugma"
   },
   {
      "id":219,
      "reward":"magcargo"
   },
   {
      "id":220,
      "reward":"swinub"
   },
   {
      "id":221,
      "reward":"piloswine"
   },
   {
      "id":222,
      "reward":"corsola"
   },
   {
      "id":223,
      "reward":"remoraid"
   },
   {
      "id":224,
      "reward":"octillery"
   },
   {
      "id":225,
      "reward":"delibird",
      "shiny":true
   },
   {
      "id":226,
      "reward":"mantine"
   },
   {
      "id":227,
      "reward":"skarmory"
   },
   {
      "id":228,
      "reward":"houndour",
      "shiny":true
   },
   {
      "id":229,
      "reward":"houndoom",
      "shiny":true
   },
   {
      "id":230,
      "reward":"kingdra"
   },
   {
      "id":231,
      "reward":"phanpy"
   },
   {
      "id":232,
      "reward":"donphan"
   },
   {
      "id":233,
      "reward":"porygon2"
   },
   {
      "id":234,
      "reward":"stantler"
   },
   {
      "id":235,
      "reward":"smeargle"
   },
   {
      "id":236,
      "reward":"tyrogue"
   },
   {
      "id":237,
      "reward":"hitmontop"
   },
   {
      "id":238,
      "reward":"smoochum"
   },
   {
      "id":239,
      "reward":"elekid",
      "shiny":true
   },
   {
      "id":240,
      "reward":"magby",
      "shiny":true
   },
   {
      "id":241,
      "reward":"miltank"
   },
   {
      "id":242,
      "reward":"blissey"
   },
   {
      "id":243,
      "reward":"raikou"
   },
   {
      "id":244,
      "reward":"entei"
   },
   {
      "id":245,
      "reward":"suicune"
   },
   {
      "id":246,
      "reward":"larvitar",
      "shiny":true
   },
   {
      "id":247,
      "reward":"pupitar",
      "shiny":true
   },
   {
      "id":248,
      "reward":"tyranitar",
      "shiny":true
   },
   {
      "id":249,
      "reward":"lugia",
      "shiny":true
   },
   {
      "id":250,
      "reward":"ho-oh",
      "shiny":true
   },
   {
      "id":251,
      "reward":"celebi"
   },
   {
      "id":252,
      "reward":"treecko"
   },
   {
      "id":253,
      "reward":"grovyle"
   },
   {
      "id":254,
      "reward":"sceptile"
   },
   {
      "id":255,
      "reward":"torchic"
   },
   {
      "id":256,
      "reward":"combusken"
   },
   {
      "id":257,
      "reward":"blaziken"
   },
   {
      "id":258,
      "reward":"mudkip"
   },
   {
      "id":259,
      "reward":"marshtomp"
   },
   {
      "id":260,
      "reward":"swampert"
   },
   {
      "id":261,
      "reward":"poochyena",
      "shiny":true
   },
   {
      "id":262,
      "reward":"mightyena",
      "shiny":true
   },
   {
      "id":263,
      "reward":"zigzagoon",
      "shiny":true
   },
   {
      "id":264,
      "reward":"linoone",
      "shiny":true
   },
   {
      "id":265,
      "reward":"wurmple"
   },
   {
      "id":266,
      "reward":"silcoon"
   },
   {
      "id":267,
      "reward":"beautifly"
   },
   {
      "id":268,
      "reward":"cascoon"
   },
   {
      "id":269,
      "reward":"dustox"
   },
   {
      "id":270,
      "reward":"lotad"
   },
   {
      "id":271,
      "reward":"lombre"
   },
   {
      "id":272,
      "reward":"ludicolo"
   },
   {
      "id":273,
      "reward":"seedot"
   },
   {
      "id":274,
      "reward":"nuzleaf"
   },
   {
      "id":275,
      "reward":"shiftry"
   },
   {
      "id":276,
      "reward":"taillow",
      "shiny":true
   },
   {
      "id":277,
      "reward":"swellow",
      "shiny":true
   },
   {
      "id":278,
      "reward":"wingull",
      "shiny":true
   },
   {
      "id":279,
      "reward":"pelipper",
      "shiny":true
   },
   {
      "id":280,
      "reward":"ralts"
   },
   {
      "id":281,
      "reward":"kirlia"
   },
   {
      "id":282,
      "reward":"gardevoir"
   },
   {
      "id":283,
      "reward":"surskit"
   },
   {
      "id":284,
      "reward":"masquerain"
   },
   {
      "id":285,
      "reward":"shroomish"
   },
   {
      "id":286,
      "reward":"breloom"
   },
   {
      "id":287,
      "reward":"slakoth"
   },
   {
      "id":288,
      "reward":"vigoroth"
   },
   {
      "id":289,
      "reward":"slaking"
   },
   {
      "id":290,
      "reward":"nincada"
   },
   {
      "id":291,
      "reward":"ninjask"
   },
   {
      "id":292,
      "reward":"shedinja"
   },
   {
      "id":293,
      "reward":"whismur"
   },
   {
      "id":294,
      "reward":"loudred"
   },
   {
      "id":295,
      "reward":"exploud"
   },
   {
      "id":296,
      "reward":"makuhita",
      "shiny":true
   },
   {
      "id":297,
      "reward":"hariyama",
      "shiny":true
   },
   {
      "id":298,
      "reward":"azurill",
      "shiny":true
   },
   {
      "id":299,
      "reward":"nosepass"
   },
   {
      "id":300,
      "reward":"skitty"
   },
   {
      "id":301,
      "reward":"delcatty"
   },
   {
      "id":302,
      "reward":"sableye",
      "shiny":true
   },
   {
      "id":303,
      "reward":"mawile",
      "shiny":true
   },
   {
      "id":304,
      "reward":"aron",
      "shiny":true
   },
   {
      "id":305,
      "reward":"lairon",
      "shiny":true
   },
   {
      "id":306,
      "reward":"aggron",
      "shiny":true
   },
   {
      "id":307,
      "reward":"meditite",
      "shiny":true
   },
   {
      "id":308,
      "reward":"medicham",
      "shiny":true
   },
   {
      "id":309,
      "reward":"electrike"
   },
   {
      "id":310,
      "reward":"manectric"
   },
   {
      "id":311,
      "reward":"plusle",
      "shiny":true
   },
   {
      "id":312,
      "reward":"minun",
      "shiny":true
   },
   {
      "id":313,
      "reward":"volbeat"
   },
   {
      "id":314,
      "reward":"illumise"
   },
   {
      "id":315,
      "reward":"roselia",
      "shiny":true
   },
   {
      "id":316,
      "reward":"gulpin"
   },
   {
      "id":317,
      "reward":"swalot"
   },
   {
      "id":318,
      "reward":"carvanha"
   },
   {
      "id":319,
      "reward":"sharpedo"
   },
   {
      "id":320,
      "reward":"wailmer",
      "shiny":true
   },
   {
      "id":321,
      "reward":"wailord",
      "shiny":true
   },
   {
      "id":322,
      "reward":"numel"
   },
   {
      "id":323,
      "reward":"camerupt"
   },
   {
      "id":324,
      "reward":"torkoal"
   },
   {
      "id":325,
      "reward":"spoink"
   },
   {
      "id":326,
      "reward":"grumpig"
   },
   {
      "id":327,
      "reward":"spinda"
   },
   {
      "id":328,
      "reward":"trapinch"
   },
   {
      "id":329,
      "reward":"vibrava"
   },
   {
      "id":330,
      "reward":"flygon"
   },
   {
      "id":331,
      "reward":"cacnea"
   },
   {
      "id":332,
      "reward":"cacturne"
   },
   {
      "id":333,
      "reward":"swablu",
      "shiny":true
   },
   {
      "id":334,
      "reward":"altaria",
      "shiny":true
   },
   {
      "id":335,
      "reward":"zangoose"
   },
   {
      "id":336,
      "reward":"seviper"
   },
   {
      "id":337,
      "reward":"lunatone"
   },
   {
      "id":338,
      "reward":"solrock"
   },
   {
      "id":339,
      "reward":"barboach"
   },
   {
      "id":340,
      "reward":"whiscash"
   },
   {
      "id":341,
      "reward":"corphish"
   },
   {
      "id":342,
      "reward":"crawdaunt"
   },
   {
      "id":343,
      "reward":"baltoy"
   },
   {
      "id":344,
      "reward":"claydol"
   },
   {
      "id":345,
      "reward":"lileep"
   },
   {
      "id":346,
      "reward":"cradily"
   },
   {
      "id":347,
      "reward":"anorith"
   },
   {
      "id":348,
      "reward":"armaldo"
   },
   {
      "id":349,
      "reward":"feebas",
      "shiny":true
   },
   {
      "id":350,
      "reward":"milotic",
      "shiny":true
   },
   {
      "id":351,
      "reward":"castform"
   },
   {
      "id":352,
      "reward":"kecleon"
   },
   {
      "id":353,
      "reward":"shuppet",
      "shiny":true
   },
   {
      "id":354,
      "reward":"banette",
      "shiny":true
   },
   {
      "id":355,
      "reward":"duskull",
      "shiny":true
   },
   {
      "id":356,
      "reward":"dusclops",
      "shiny":true
   },
   {
      "id":357,
      "reward":"tropius"
   },
   {
      "id":358,
      "reward":"chimecho"
   },
   {
      "id":359,
      "reward":"absol",
      "shiny":true
   },
   {
      "id":360,
      "reward":"wynaut"
   },
   {
      "id":361,
      "reward":"snorunt",
      "shiny":true
   },
   {
      "id":362,
      "reward":"glalie",
      "shiny":true
   },
   {
      "id":363,
      "reward":"spheal"
   },
   {
      "id":364,
      "reward":"sealeo"
   },
   {
      "id":365,
      "reward":"walrein"
   },
   {
      "id":366,
      "reward":"clamperl"
   },
   {
      "id":367,
      "reward":"huntail"
   },
   {
      "id":368,
      "reward":"gorebyss"
   },
   {
      "id":369,
      "reward":"relicanth"
   },
   {
      "id":370,
      "reward":"luvdisc",
      "shiny":true
   },
   {
      "id":371,
      "reward":"bagon"
   },
   {
      "id":372,
      "reward":"shelgon"
   },
   {
      "id":373,
      "reward":"salamence"
   },
   {
      "id":374,
      "reward":"beldum",
      "shiny":true
   },
   {
      "id":375,
      "reward":"metang",
      "shiny":true
   },
   {
      "id":376,
      "reward":"metagross",
      "shiny":true
   },
   {
      "id":377,
      "reward":"regirock"
   },
   {
      "id":378,
      "reward":"regice"
   },
   {
      "id":379,
      "reward":"registeel"
   },
   {
      "id":380,
      "reward":"latias"
   },
   {
      "id":381,
      "reward":"latios"
   },
   {
      "id":382,
      "reward":"kyogre",
      "shiny":true
   },
   {
      "id":383,
      "reward":"groudon",
      "shiny":true
   },
   {
      "id":384,
      "reward":"rayquaza"
   },
   {
      "id":385,
      "reward":"jirachi"
   },
   {
      "id":386,
      "reward":"deoxys"
   },
   {
      "id":387,
      "reward":"turtwig"
   },
   {
      "id":388,
      "reward":"grotle"
   },
   {
      "id":389,
      "reward":"torterra"
   },
   {
      "id":390,
      "reward":"chimchar"
   },
   {
      "id":391,
      "reward":"monferno"
   },
   {
      "id":392,
      "reward":"infernape"
   },
   {
      "id":393,
      "reward":"piplup"
   },
   {
      "id":394,
      "reward":"prinplup"
   },
   {
      "id":395,
      "reward":"empoleon"
   },
   {
      "id":396,
      "reward":"starly"
   },
   {
      "id":397,
      "reward":"staravia"
   },
   {
      "id":398,
      "reward":"staraptor"
   },
   {
      "id":399,
      "reward":"bidoof"
   },
   {
      "id":400,
      "reward":"bibarel"
   },
   {
      "id":401,
      "reward":"kricketot"
   },
   {
      "id":402,
      "reward":"kricketune"
   },
   {
      "id":403,
      "reward":"shinx",
      "shiny":true
   },
   {
      "id":404,
      "reward":"luxio",
      "shiny":true
   },
   {
      "id":405,
      "reward":"luxray",
      "shiny":true
   },
   {
      "id":406,
      "reward":"budew",
      "shiny":true
   },
   {
      "id":407,
      "reward":"roserade",
      "shiny":true
   },
   {
      "id":408,
      "reward":"cranidos"
   },
   {
      "id":409,
      "reward":"rampardos"
   },
   {
      "id":410,
      "reward":"shieldon"
   },
   {
      "id":411,
      "reward":"bastiodon"
   },
   {
      "id":412,
      "reward":"burmy"
   },
   {
      "id":413,
      "reward":"wormadam"
   },
   {
      "id":414,
      "reward":"mothim"
   },
   {
      "id":415,
      "reward":"combee"
   },
   {
      "id":416,
      "reward":"vespiquen"
   },
   {
      "id":417,
      "reward":"pachirisu"
   },
   {
      "id":418,
      "reward":"buizel"
   },
   {
      "id":419,
      "reward":"floatzel"
   },
   {
      "id":420,
      "reward":"cherubi"
   },
   {
      "id":421,
      "reward":"cherrim"
   },
   {
      "id":422,
      "reward":"shellos"
   },
   {
      "id":423,
      "reward":"gastrodon"
   },
   {
      "id":424,
      "reward":"ambipom"
   },
   {
      "id":425,
      "reward":"drifloon",
      "shiny":true
   },
   {
      "id":426,
      "reward":"drifblim",
      "shiny":true
   },
   {
      "id":427,
      "reward":"buneary"
   },
   {
      "id":428,
      "reward":"lopunny"
   },
   {
      "id":429,
      "reward":"mismagius",
      "shiny":true
   },
   {
      "id":430,
      "reward":"honchkrow",
      "shiny":true
   },
   {
      "id":431,
      "reward":"glameow"
   },
   {
      "id":432,
      "reward":"purugly"
   },
   {
      "id":433,
      "reward":"chingling"
   },
   {
      "id":434,
      "reward":"stunky"
   },
   {
      "id":435,
      "reward":"skuntank"
   },
   {
      "id":436,
      "reward":"bronzor"
   },
   {
      "id":437,
      "reward":"bronzong"
   },
   {
      "id":438,
      "reward":"bonsly"
   },
   {
      "id":439,
      "reward":"mime-jr"
   },
   {
      "id":440,
      "reward":"happiny"
   },
   {
      "id":441,
      "reward":"chatot"
   },
   {
      "id":442,
      "reward":"spiritomb"
   },
   {
      "id":443,
      "reward":"gible"
   },
   {
      "id":444,
      "reward":"gabite"
   },
   {
      "id":445,
      "reward":"garchomp"
   },
   {
      "id":446,
      "reward":"munchlax"
   },
   {
      "id":447,
      "reward":"riolu"
   },
   {
      "id":448,
      "reward":"lucario"
   },
   {
      "id":449,
      "reward":"hippopotas"
   },
   {
      "id":450,
      "reward":"hippowdon"
   },
   {
      "id":451,
      "reward":"skorupi"
   },
   {
      "id":452,
      "reward":"drapion"
   },
   {
      "id":453,
      "reward":"croagunk"
   },
   {
      "id":454,
      "reward":"toxicroak"
   },
   {
      "id":455,
      "reward":"carnivine"
   },
   {
      "id":456,
      "reward":"finneon"
   },
   {
      "id":457,
      "reward":"lumineon"
   },
   {
      "id":458,
      "reward":"mantyke"
   },
   {
      "id":459,
      "reward":"snover"
   },
   {
      "id":460,
      "reward":"abomasnow"
   },
   {
      "id":461,
      "reward":"weavile"
   },
   {
      "id":462,
      "reward":"magnezone",
      "shiny":true
   },
   {
      "id":463,
      "reward":"lickilicky"
   },
   {
      "id":464,
      "reward":"rhyperior"
   },
   {
      "id":465,
      "reward":"tangrowth"
   },
   {
      "id":466,
      "reward":"electivire",
      "shiny":true
   },
   {
      "id":467,
      "reward":"magmortar",
      "shiny":true
   },
   {
      "id":468,
      "reward":"togekiss",
      "shiny":true
   },
   {
      "id":469,
      "reward":"yanmega"
   },
   {
      "id":470,
      "reward":"leafeon",
      "shiny":true
   },
   {
      "id":471,
      "reward":"glaceon",
      "shiny":true
   },
   {
      "id":472,
      "reward":"gliscor"
   },
   {
      "id":473,
      "reward":"mamoswine"
   },
   {
      "id":474,
      "reward":"porygon-z"
   },
   {
      "id":475,
      "reward":"gallade",
      "shiny":true
   },
   {
      "id":476,
      "reward":"probopass"
   },
   {
      "id":477,
      "reward":"dusknoir",
      "shiny":true
   },
   {
      "id":478,
      "reward":"froslass",
      "shiny":true
   },
   {
      "id":479,
      "reward":"rotom"
   },
   {
      "id":480,
      "reward":"uxie"
   },
   {
      "id":481,
      "reward":"mesprit"
   },
   {
      "id":482,
      "reward":"azelf"
   },
   {
      "id":483,
      "reward":"dialga"
   },
   {
      "id":484,
      "reward":"palkia"
   },
   {
      "id":485,
      "reward":"heatran"
   },
   {
      "id":486,
      "reward":"regigigas"
   },
   {
      "id":487,
      "reward":"giratina-altered"
   },
   {
      "id":488,
      "reward":"cresselia"
   },
   {
      "id":489,
      "reward":"phione"
   },
   {
      "id":490,
      "reward":"manaphy"
   },
   {
      "id":491,
      "reward":"darkrai"
   },
   {
      "id":492,
      "reward":"shaymin-land"
   },
   {
      "id":493,
      "reward":"arceus"
   },
   {
      "id":494,
      "reward":"victini"
   },
   {
      "id":495,
      "reward":"snivy"
   },
   {
      "id":496,
      "reward":"servine"
   },
   {
      "id":497,
      "reward":"serperior"
   },
   {
      "id":498,
      "reward":"tepig"
   },
   {
      "id":499,
      "reward":"pignite"
   },
   {
      "id":500,
      "reward":"emboar"
   },
   {
      "id":501,
      "reward":"oshawott"
   },
   {
      "id":502,
      "reward":"dewott"
   },
   {
      "id":503,
      "reward":"samurott"
   },
   {
      "id":504,
      "reward":"patrat"
   },
   {
      "id":505,
      "reward":"watchog"
   },
   {
      "id":506,
      "reward":"lillipup"
   },
   {
      "id":507,
      "reward":"herdier"
   },
   {
      "id":508,
      "reward":"stoutland"
   },
   {
      "id":509,
      "reward":"purrloin"
   },
   {
      "id":510,
      "reward":"liepard"
   },
   {
      "id":511,
      "reward":"pansage"
   },
   {
      "id":512,
      "reward":"simisage"
   },
   {
      "id":513,
      "reward":"pansear"
   },
   {
      "id":514,
      "reward":"simisear"
   },
   {
      "id":515,
      "reward":"panpour"
   },
   {
      "id":516,
      "reward":"simipour"
   },
   {
      "id":517,
      "reward":"munna"
   },
   {
      "id":518,
      "reward":"musharna"
   },
   {
      "id":519,
      "reward":"pidove"
   },
   {
      "id":520,
      "reward":"tranquill"
   },
   {
      "id":521,
      "reward":"unfezant"
   },
   {
      "id":522,
      "reward":"blitzle"
   },
   {
      "id":523,
      "reward":"zebstrika"
   },
   {
      "id":524,
      "reward":"roggenrola"
   },
   {
      "id":525,
      "reward":"boldore"
   },
   {
      "id":526,
      "reward":"gigalith"
   },
   {
      "id":527,
      "reward":"woobat"
   },
   {
      "id":528,
      "reward":"swoobat"
   },
   {
      "id":529,
      "reward":"drilbur"
   },
   {
      "id":530,
      "reward":"excadrill"
   },
   {
      "id":531,
      "reward":"audino"
   },
   {
      "id":532,
      "reward":"timburr"
   },
   {
      "id":533,
      "reward":"gurdurr"
   },
   {
      "id":534,
      "reward":"conkeldurr"
   },
   {
      "id":535,
      "reward":"tympole"
   },
   {
      "id":536,
      "reward":"palpitoad"
   },
   {
      "id":537,
      "reward":"seismitoad"
   },
   {
      "id":538,
      "reward":"throh"
   },
   {
      "id":539,
      "reward":"sawk"
   },
   {
      "id":540,
      "reward":"sewaddle"
   },
   {
      "id":541,
      "reward":"swadloon"
   },
   {
      "id":542,
      "reward":"leavanny"
   },
   {
      "id":543,
      "reward":"venipede"
   },
   {
      "id":544,
      "reward":"whirlipede"
   },
   {
      "id":545,
      "reward":"scolipede"
   },
   {
      "id":546,
      "reward":"cottonee"
   },
   {
      "id":547,
      "reward":"whimsicott"
   },
   {
      "id":548,
      "reward":"petilil"
   },
   {
      "id":549,
      "reward":"lilligant"
   },
   {
      "id":550,
      "reward":"basculin"
   },
   {
      "id":551,
      "reward":"sandile"
   },
   {
      "id":552,
      "reward":"krokorok"
   },
   {
      "id":553,
      "reward":"krookodile"
   },
   {
      "id":554,
      "reward":"darumaka"
   },
   {
      "id":555,
      "reward":"darmanitan"
   },
   {
      "id":556,
      "reward":"maractus"
   },
   {
      "id":557,
      "reward":"dwebble"
   },
   {
      "id":558,
      "reward":"crustle"
   },
   {
      "id":559,
      "reward":"scraggy"
   },
   {
      "id":560,
      "reward":"scrafty"
   },
   {
      "id":561,
      "reward":"sigilyph"
   },
   {
      "id":562,
      "reward":"yamask"
   },
   {
      "id":563,
      "reward":"cofagrigus"
   },
   {
      "id":564,
      "reward":"tirtouga"
   },
   {
      "id":565,
      "reward":"carracosta"
   },
   {
      "id":566,
      "reward":"archen"
   },
   {
      "id":567,
      "reward":"archeops"
   },
   {
      "id":568,
      "reward":"trubbish"
   },
   {
      "id":569,
      "reward":"garbodor"
   },
   {
      "id":570,
      "reward":"zorua"
   },
   {
      "id":571,
      "reward":"zoroark"
   },
   {
      "id":572,
      "reward":"minccino"
   },
   {
      "id":573,
      "reward":"cinccino"
   },
   {
      "id":574,
      "reward":"gothita"
   },
   {
      "id":575,
      "reward":"gothorita"
   },
   {
      "id":576,
      "reward":"gothitelle"
   },
   {
      "id":577,
      "reward":"solosis"
   },
   {
      "id":578,
      "reward":"duosion"
   },
   {
      "id":579,
      "reward":"reuniclus"
   },
   {
      "id":580,
      "reward":"ducklett"
   },
   {
      "id":581,
      "reward":"swanna"
   },
   {
      "id":582,
      "reward":"vanillite"
   },
   {
      "id":583,
      "reward":"vanillish"
   },
   {
      "id":584,
      "reward":"vanilluxe"
   },
   {
      "id":585,
      "reward":"deerling"
   },
   {
      "id":586,
      "reward":"sawsbuck"
   },
   {
      "id":587,
      "reward":"emolga"
   },
   {
      "id":588,
      "reward":"karrablast"
   },
   {
      "id":589,
      "reward":"escavalier"
   },
   {
      "id":590,
      "reward":"foongus"
   },
   {
      "id":591,
      "reward":"amoonguss"
   },
   {
      "id":592,
      "reward":"frillish"
   },
   {
      "id":593,
      "reward":"jellicent"
   },
   {
      "id":594,
      "reward":"alomomola"
   },
   {
      "id":595,
      "reward":"joltik"
   },
   {
      "id":596,
      "reward":"galvantula"
   },
   {
      "id":597,
      "reward":"ferroseed"
   },
   {
      "id":598,
      "reward":"ferrothorn"
   },
   {
      "id":599,
      "reward":"klink"
   },
   {
      "id":600,
      "reward":"klang"
   },
   {
      "id":601,
      "reward":"klinklang"
   },
   {
      "id":602,
      "reward":"tynamo"
   },
   {
      "id":603,
      "reward":"eelektrik"
   },
   {
      "id":604,
      "reward":"eelektross"
   },
   {
      "id":605,
      "reward":"elgyem"
   },
   {
      "id":606,
      "reward":"beheeyem"
   },
   {
      "id":607,
      "reward":"litwick"
   },
   {
      "id":608,
      "reward":"lampent"
   },
   {
      "id":609,
      "reward":"chandelure"
   },
   {
      "id":610,
      "reward":"axew"
   },
   {
      "id":611,
      "reward":"fraxure"
   },
   {
      "id":612,
      "reward":"haxorus"
   },
   {
      "id":613,
      "reward":"cubchoo"
   },
   {
      "id":614,
      "reward":"beartic"
   },
   {
      "id":615,
      "reward":"cryogonal"
   },
   {
      "id":616,
      "reward":"shelmet"
   },
   {
      "id":617,
      "reward":"accelgor"
   },
   {
      "id":618,
      "reward":"stunfisk"
   },
   {
      "id":619,
      "reward":"mienfoo"
   },
   {
      "id":620,
      "reward":"mienshao"
   },
   {
      "id":621,
      "reward":"druddigon"
   },
   {
      "id":622,
      "reward":"golett"
   },
   {
      "id":623,
      "reward":"golurk"
   },
   {
      "id":624,
      "reward":"pawniard"
   },
   {
      "id":625,
      "reward":"bisharp"
   },
   {
      "id":626,
      "reward":"bouffalant"
   },
   {
      "id":627,
      "reward":"rufflet"
   },
   {
      "id":628,
      "reward":"braviary"
   },
   {
      "id":629,
      "reward":"vullaby"
   },
   {
      "id":630,
      "reward":"mandibuzz"
   },
   {
      "id":631,
      "reward":"heatmor"
   },
   {
      "id":632,
      "reward":"durant"
   },
   {
      "id":633,
      "reward":"deino"
   },
   {
      "id":634,
      "reward":"zweilous"
   },
   {
      "id":635,
      "reward":"hydreigon"
   },
   {
      "id":636,
      "reward":"larvesta"
   },
   {
      "id":637,
      "reward":"volcarona"
   },
   {
      "id":638,
      "reward":"cobalion"
   },
   {
      "id":639,
      "reward":"terrakion"
   },
   {
      "id":640,
      "reward":"virizion"
   },
   {
      "id":641,
      "reward":"tornadus"
   },
   {
      "id":642,
      "reward":"thundurus"
   },
   {
      "id":643,
      "reward":"reshiram"
   },
   {
      "id":644,
      "reward":"zekrom"
   },
   {
      "id":645,
      "reward":"landorus"
   },
   {
      "id":646,
      "reward":"kyurem"
   },
   {
      "id":647,
      "reward":"keldeo"
   },
   {
      "id":648,
      "reward":"meloetta"
   },
   {
      "id":649,
      "reward":"genesect"
   },
   {
      "id":650,
      "reward":"chespin"
   },
   {
      "id":651,
      "reward":"quilladin"
   },
   {
      "id":652,
      "reward":"chesnaught"
   },
   {
      "id":653,
      "reward":"fennekin"
   },
   {
      "id":654,
      "reward":"braixen"
   },
   {
      "id":655,
      "reward":"delphox"
   },
   {
      "id":656,
      "reward":"froakie"
   },
   {
      "id":657,
      "reward":"frogadier"
   },
   {
      "id":658,
      "reward":"greninja"
   },
   {
      "id":659,
      "reward":"bunnelby"
   },
   {
      "id":660,
      "reward":"diggersby"
   },
   {
      "id":661,
      "reward":"fletchling"
   },
   {
      "id":662,
      "reward":"fletchinder"
   },
   {
      "id":663,
      "reward":"talonflame"
   },
   {
      "id":664,
      "reward":"scatterbug"
   },
   {
      "id":665,
      "reward":"spewpa"
   },
   {
      "id":666,
      "reward":"vivillon"
   },
   {
      "id":667,
      "reward":"litleo"
   },
   {
      "id":668,
      "reward":"pyroar"
   },
   {
      "id":669,
      "reward":"flabebe"
   },
   {
      "id":670,
      "reward":"floette"
   },
   {
      "id":671,
      "reward":"florges"
   },
   {
      "id":672,
      "reward":"skiddo"
   },
   {
      "id":673,
      "reward":"gogoat"
   },
   {
      "id":674,
      "reward":"pancham"
   },
   {
      "id":675,
      "reward":"pangoro"
   },
   {
      "id":676,
      "reward":"furfrou"
   },
   {
      "id":677,
      "reward":"espurr"
   },
   {
      "id":678,
      "reward":"meowstic"
   },
   {
      "id":679,
      "reward":"honedge"
   },
   {
      "id":680,
      "reward":"doublade"
   },
   {
      "id":681,
      "reward":"aegislash"
   },
   {
      "id":682,
      "reward":"spritzee"
   },
   {
      "id":683,
      "reward":"aromatisse"
   },
   {
      "id":684,
      "reward":"swirlix"
   },
   {
      "id":685,
      "reward":"slurpuff"
   },
   {
      "id":686,
      "reward":"inkay"
   },
   {
      "id":687,
      "reward":"malamar"
   },
   {
      "id":688,
      "reward":"binacle"
   },
   {
      "id":689,
      "reward":"barbaracle"
   },
   {
      "id":690,
      "reward":"skrelp"
   },
   {
      "id":691,
      "reward":"dragalge"
   },
   {
      "id":692,
      "reward":"clauncher"
   },
   {
      "id":693,
      "reward":"clawitzer"
   },
   {
      "id":694,
      "reward":"helioptile"
   },
   {
      "id":695,
      "reward":"heliolisk"
   },
   {
      "id":696,
      "reward":"tyrunt"
   },
   {
      "id":697,
      "reward":"tyrantrum"
   },
   {
      "id":698,
      "reward":"amaura"
   },
   {
      "id":699,
      "reward":"aurorus"
   },
   {
      "id":700,
      "reward":"sylveon"
   },
   {
      "id":701,
      "reward":"hawlucha"
   },
   {
      "id":702,
      "reward":"dedenne"
   },
   {
      "id":703,
      "reward":"carbink"
   },
   {
      "id":704,
      "reward":"goomy"
   },
   {
      "id":705,
      "reward":"sliggoo"
   },
   {
      "id":706,
      "reward":"goodra"
   },
   {
      "id":707,
      "reward":"klefki"
   },
   {
      "id":708,
      "reward":"phantump"
   },
   {
      "id":709,
      "reward":"trevenant"
   },
   {
      "id":710,
      "reward":"pumpkaboo"
   },
   {
      "id":711,
      "reward":"gourgeist"
   },
   {
      "id":712,
      "reward":"bergmite"
   },
   {
      "id":713,
      "reward":"avalugg"
   },
   {
      "id":714,
      "reward":"noibat"
   },
   {
      "id":715,
      "reward":"noivern"
   },
   {
      "id":716,
      "reward":"xerneas"
   },
   {
      "id":717,
      "reward":"yveltal"
   },
   {
      "id":718,
      "reward":"zygarde"
   },
   {
      "id":719,
      "reward":"diancie"
   },
   {
      "id":720,
      "reward":"hoopa"
   },
   {
      "id":721,
      "reward":"volcanion"
   },
   {
      "id":722,
      "reward":"rowlet"
   },
   {
      "id":723,
      "reward":"dartrix"
   },
   {
      "id":724,
      "reward":"decidueye"
   },
   {
      "id":725,
      "reward":"litten"
   },
   {
      "id":726,
      "reward":"torracat"
   },
   {
      "id":727,
      "reward":"incineroar"
   },
   {
      "id":728,
      "reward":"popplio"
   },
   {
      "id":729,
      "reward":"brionne"
   },
   {
      "id":730,
      "reward":"primarina"
   },
   {
      "id":731,
      "reward":"pikipek"
   },
   {
      "id":732,
      "reward":"trumbeak"
   },
   {
      "id":733,
      "reward":"toucannon"
   },
   {
      "id":734,
      "reward":"yungoos"
   },
   {
      "id":735,
      "reward":"gumshoos"
   },
   {
      "id":736,
      "reward":"grubbin"
   },
   {
      "id":737,
      "reward":"charjabug"
   },
   {
      "id":738,
      "reward":"vikavolt"
   },
   {
      "id":739,
      "reward":"crabrawler"
   },
   {
      "id":740,
      "reward":"crabominable"
   },
   {
      "id":741,
      "reward":"oricorio-baile"
   },
   {
      "id":742,
      "reward":"cutiefly"
   },
   {
      "id":743,
      "reward":"ribombee"
   },
   {
      "id":744,
      "reward":"rockruff"
   },
   {
      "id":745,
      "reward":"lycanroc"
   },
   {
      "id":746,
      "reward":"wishiwashi"
   },
   {
      "id":747,
      "reward":"mareanie"
   },
   {
      "id":748,
      "reward":"toxapex"
   },
   {
      "id":749,
      "reward":"mudbray"
   },
   {
      "id":750,
      "reward":"mudsdale"
   },
   {
      "id":751,
      "reward":"dewpider"
   },
   {
      "id":752,
      "reward":"araquanid"
   },
   {
      "id":753,
      "reward":"fomantis"
   },
   {
      "id":754,
      "reward":"lurantis"
   },
   {
      "id":755,
      "reward":"morelull"
   },
   {
      "id":756,
      "reward":"shiinotic"
   },
   {
      "id":757,
      "reward":"salandit"
   },
   {
      "id":758,
      "reward":"salazzle"
   },
   {
      "id":759,
      "reward":"stufful"
   },
   {
      "id":760,
      "reward":"bewear"
   },
   {
      "id":761,
      "reward":"bounsweet"
   },
   {
      "id":762,
      "reward":"steenee"
   },
   {
      "id":763,
      "reward":"tsareena"
   },
   {
      "id":764,
      "reward":"comfey"
   },
   {
      "id":765,
      "reward":"oranguru"
   },
   {
      "id":766,
      "reward":"passimian"
   },
   {
      "id":767,
      "reward":"wimpod"
   },
   {
      "id":768,
      "reward":"golisopod"
   },
   {
      "id":769,
      "reward":"sandygast"
   },
   {
      "id":770,
      "reward":"palossand"
   },
   {
      "id":771,
      "reward":"pyukumuku"
   },
   {
      "id":772,
      "reward":"type-null"
   },
   {
      "id":773,
      "reward":"silvally"
   },
   {
      "id":774,
      "reward":"minior"
   },
   {
      "id":775,
      "reward":"komala"
   },
   {
      "id":776,
      "reward":"turtonator"
   },
   {
      "id":777,
      "reward":"togedemaru"
   },
   {
      "id":778,
      "reward":"mimikyu"
   },
   {
      "id":779,
      "reward":"bruxish"
   },
   {
      "id":780,
      "reward":"drampa"
   },
   {
      "id":781,
      "reward":"dhelmise"
   },
   {
      "id":782,
      "reward":"jangmo-o"
   },
   {
      "id":783,
      "reward":"hakamo-o"
   },
   {
      "id":784,
      "reward":"kommo-o"
   },
   {
      "id":785,
      "reward":"tapu-koko"
   },
   {
      "id":786,
      "reward":"tapu-lele"
   },
   {
      "id":787,
      "reward":"tapu-bulu"
   },
   {
      "id":788,
      "reward":"tapu-fini"
   },
   {
      "id":789,
      "reward":"cosmog"
   },
   {
      "id":790,
      "reward":"cosmoem"
   },
   {
      "id":791,
      "reward":"solgaleo"
   },
   {
      "id":792,
      "reward":"lunala"
   },
   {
      "id":793,
      "reward":"nihilego"
   },
   {
      "id":794,
      "reward":"buzzwole"
   },
   {
      "id":795,
      "reward":"pheromosa"
   },
   {
      "id":796,
      "reward":"xurkitree"
   },
   {
      "id":797,
      "reward":"celesteela"
   },
   {
      "id":798,
      "reward":"kartana"
   },
   {
      "id":799,
      "reward":"guzzlord"
   },
   {
      "id":800,
      "reward":"necrozma"
   },
   {
      "id":801,
      "reward":"magearna"
   },
   {
      "id":802,
      "reward":"marshadow"
   },
   {
      "id":803,
      "reward":"poipole"
   },
   {
      "id":804,
      "reward":"naganadel"
   },
   {
      "id":805,
      "reward":"stakataka"
   },
   {
      "id":806,
      "reward":"blacephalon"
   },
   {
      "id":807,
      "reward":"zeraora"
   },
   {
      "id":10000,
      "reward":"Balls, Berries, or Stardust",
      "icon": "icon_trash"
   },
   {
      "id":10001,
      "reward":"Stardust (1000+)",
      "icon": "icon_stardust"
   },
   {
      "id":10002,
      "reward":"Rare Candy",
      "icon": "icon_rare_candy"
   },
   {
      "id":10003,
      "reward":"Golden Razz Berry",
      "icon":"icon_golden_razz"
   },
   {
      "id":10004,
      "reward":"Silver Pinap",
      "icon":"icon_silver_pinap"
   }
];

var quest_rewards = [
  {
    "quest_id": 1,
    "reward_id": 10000
  },
  {
    "quest_id": 1,
    "reward_id": 10001
  },
  {
    "quest_id": 1,
    "reward_id": 10002
  },
  {
    "quest_id": 1,
    "reward_id": 10003
  },
  {
    "quest_id": 2,
    "reward_id": 10004
  },
  {
    "quest_id": 3,
    "reward_id": 10004
  },
  {
    "quest_id": 4,
    "reward_id": 104
  }
];

updateQuests();